name: CREATOR CI

on:
  push:
    branches: ["main", "ci"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build CREATOR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.22
      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.5.2
      - name: Build compiler web
        run: |
          cd CreatorCompiler
          bun install -g wasm-pack
          wasm-pack build --target web
          mv pkg/* ../src/core/assembler/creatorAssembler/web/wasm/
      - name: Build compiler cli
        run: |
          cd CreatorCompiler
          deno run -A jsr:@deno/wasmbuild
          mv lib/* ../src/core/assembler/creatorAssembler/deno/wasm/
      - name: Build web
        run: |
          bun install
          bun build:web
      # - name: Build cli
      #   run: |
      #     bun run build:cli
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/web/creatorV/

  # TODO: update unit tests runner
  # creator-checker:
  #   name: Execute CREATOR Checker
  #   needs: build
  #
  #   runs-on: ubuntu-latest
  #
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #
  #   steps:
  #     - uses: pyTooling/download-artifact@v4
  #       with:
  #         name: github-pages
  #         tarball-name: artifact.tar
  #         path: .
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - name: Install dependencies
  #       run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm run test-creator-node

  deploy-pages-beta:
    name: Deploy CREATOR to GitHub Pages (development)
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request' && github.repository != 'creatorsim/creator'
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  # TODO: re-add this when the tests runner is updated
  # deploy-pages-stable:
  #   name: Deploy CREATOR to GitHub Pages (stable)
  #   runs-on: ubuntu-latest
  #   needs: creator-checker
  #   if: github.event_name != 'pull_request' && github.repository == 'creatorsim/creator'
  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       uses: actions/deploy-pages@v4
